#this is developmental version of configurations

server:
  port: 8083

#database connections
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_yt
    username: root
    password: password

#  spring.datasource.url=jdbc:postgresql://localhost:5432/your_db
#  spring.datasource.username=your_user
#  spring.datasource.password=your_password
#
#  spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#    hikari:
#      pool_name: HikariCP
#      maximum-pool-size: 5
#      connection_timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 1800000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1
#spring and hibernate configurations

jpa:
  hibernate:
    ddl-auto: update    #automatically table will ge updated when entities are there
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
  show-sql: true


logging:
  level:
    org.springframework.security: DEBUG


security:
    jwt:
      secret: ${JWT SECRET:wswjdoickaslklqsowqjhdijdlqwsqwdhkqjdlkqdlskdlskxdwjcidj}  //you can also create using environment variable
      issuer: ${JWT_ISSUER:api.substring.com}
      access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}      //60 minutes
      refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}     //24 hours
      refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
      cookie-secure: ${JWT_COOKIE_SECURE:true}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}       // Lax:Cookie sent for same-site + some safe cross-site requests
